---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: 0.10.2
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 24h
  values:
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
            - "${METALLB_ARP_RANGE}"

    # FIXME: uff esto lo copié de algún lado y no anda:
    #    reconciliation failed: Helm install failed: unable to build kubernetes
    #    objects from release manifest: [unable to recognize "": no matches for
    #    kind "PodMonitor" in version "monitoring.coreos.com/v1", unable to
    #    recognize "": no matches for kind "PrometheusRule" in version
    #    "monitoring.coreos.com/v1"]
    # prometheus:
    #   podMonitor:
    #     enabled: true
    #   prometheusRule:
    #     enabled: true
