---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: config
  namespace: flux-system
spec:
  interval: 24h00m0s
  path: ./config/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: v1
      kind: Secret
      name: cluster-secrets
      namespace: flux-system
    - apiVersion: v1
      kind: ConfigMap
      name: cluster-settings
      namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
